spring:
  datasource:
    url: jdbc:mysql://localhost:8083/insert
    username: root
    password: insertapi
    driverClassName: com.mysql.cj.jdbc.Driver
  flyway:
    enabled: true
  jpa:
    hibernate-ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
